config/routes.rb
Noexpense::Application.routes.draw do

	get "log_out" => "sessions#destroy", as: "log_out"

	get "log_in" => "sessions#new", as: "log_in"

	get "sign_up" => "users#new", as: "sign_up"

	get "incomes/index"

	get "main/index"

	
	resources :users do
		resources :expenses
		resources :incomes
	end

	resources :sessions

	 root :to => 'main#index'

end

app/models/expense.rb
class Expense < ActiveRecord::Base
	belongs_to :user
  	attr_accessible :name, :value, :expense_date

  	validates :name,  :presence => true
  	validates :value, :presence => true
end

app/models/income.rb
class Income < ActiveRecord::Base
	belongs_to :user
  	attr_accessible :income_date, :name, :value

  	validates :name,  :presence => true
  	validates :value, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  	attr_accessible :currency, :email, :password , :password_confirmation , :total_expenses 

  	attr_accessor :password
  	before_save :encrypt_password
  
  	validates_confirmation_of :password
  	validates_presence_of :password, :on => :create
  	validates_presence_of :email
  	validates_uniqueness_of :email

  	has_many :expenses, :dependent => :destroy
    has_many :incomes, :dependent => :destroy

  	def self.authenticate(email, password)
  		user = find_by_email(email)
    	if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
    		user
    	else
    		nil
    	end
  	end

  	def encrypt_password
    	if password.present?
      		self.password_salt = BCrypt::Engine.generate_salt
      		self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    	end
  	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery
	helper_method :current_user
	
	private

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
	def index
		@expenses = Expense.all
		@user = User.find(params[:user_id])
 
		respond_to do |format|
			format.html  # index.html.erb
			format.json { render json: @expenses }
  		end
  	end

	def new
		@expense = Expense.new
		@user = User.find(params[:user_id])
 
	  	respond_to do |format|
	    	format.html  # new.html.erb
	  	end
	end

  	def create
  		@user = User.find(params[:user_id])
		@expense = @user.expenses.create(params[:expense])
		redirect_to user_expenses_path(current_user)
	end

	def show
		@expense = Expense.find(params[:id])
	 
	  	respond_to do |format|
	    	format.html  # show.html.erb
	  	end
	end

	def edit
    	@expense = Expense.find(params[:id])
    	@user = User.find(params[:user_id])
  	end

  	def update
	    @expense = Expense.find(params[:id])

	    respond_to do |format|
	      	if @expense.update_attributes(params[:expense])
	        	format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
	        	format.json { head :no_content }
	      	else
	        	format.html { render action: "edit" }
	        	format.json { render json: @expense.errors, status: :unprocessable_entity }
	      	end
	    end
	end

  	def destroy
  		@user = User.find(params[:user_id])
		@expense = @user.expenses.find(params[:id])
		@expense.destroy
		redirect_to user_expenses_path(current_user)
	end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  def index
		@incomes = Income.all
		@user = User.find(params[:user_id])
 
		respond_to do |format|
			format.html  # index.html.erb
			format.json { render json: @incomes }
  		end
  	end

  	def new
		@income = Income.new
		@user = User.find(params[:user_id])
 
	  	respond_to do |format|
	    	format.html  # new.html.erb
	  	end
	end

	def create
  		@user = User.find(params[:user_id])
		@income = @user.incomes.create(params[:income])
		redirect_to user_incomes_path(current_user)
	end

	def show
		@income = Income.find(params[:id])
	 
	  	respond_to do |format|
	    	format.html  # show.html.erb
	  	end
	end

	def edit
    	@income = Income.find(params[:id])
    	@user = User.find(params[:user_id])
  	end

  	def update
    	@income = Income.find(params[:id])

	    respond_to do |format|
	    	if @income.update_attributes(params[:income])
	        	format.html { redirect_to @income, notice: 'Income was successfully updated.' }
	        	format.json { head :no_content }
	      	else
	        	format.html { render action: "edit" }
	        	format.json { render json: @income.errors, status: :unprocessable_entity }
	      	end
	    end
  	end

  	def destroy
    	@user = User.find(params[:user_id])
		@income = @user.incomes.find(params[:id])
		@income.destroy
		redirect_to user_incomes_path(current_user)
	end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  	@balance = current_user.incomes.sum('value') - current_user.expenses.sum('value')
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  	def new
  	end
  	def create
		user = User.authenticate(params[:email], params[:password])
		if user
			session[:user_id] = user.id
			redirect_to root_url
		else
			flash.now.alert = "Invalid email or password"
			render "new"
		end
  	end
  	def destroy
  		session[:user_id] = nil
		redirect_to root_url, :notice => "Logged out!"
  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
 
		respond_to do |format|
		    format.html  # index.html.erb
		    format.json  { render :json => @users }
		end
	end
	def new
		@user = User.new
	end
	def create
		@user = User.new(params[:user])
		if @user.save
			redirect_to root_url, :notice => "Signed up!"
		else
			render "new"
		end
	end
	def show
		@user = User.find(params[:id])
 
		respond_to do |format|
			format.html  # show.html.erb
		    format.json  { render :json => @user }
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/expenses/_form.html.slim
- if current_user
	= form_for ([@user, @user.expenses.build]), html: {class: "form"} do |f|
		- if @expense.errors.any?
			div id="error_explanation" class="alert alert-error"
				button type="button" class="close" data-dismiss="alert"&times;
				h4 class="center"
					= pluralize(@expense.errors.count, "error")
					| &nbsp;!
				ul
					- @expense.errors.full_messages.each do |msg|
						li class="list-style-none center" = msg
					end
		end
		fieldset class="center"
			= f.text_field :name, value: controller.action_name == 'edit' || controller.action_name == 'update'  ? @expense.name : @expense.name, class: "span6", placeholder: "Expense name"
			br
			= f.text_field :value, value: controller.action_name == 'edit' || controller.action_name == 'update'  ? number_to_currency(@expense.value, unit: " ") : number_to_currency(@expense.value, unit: " "), class: "span6", placeholder: "Amount"
			br
			= f.submit 'Add', class: 'btn btn-large btn-success span6'   		
	end
- else
	div class="row-fluid"		
		h3 class="span6 centered" Log in or sign up to add new expense!
		hr
end

app/views/expenses/edit.html.slim
div class="row-fluid"
	div class="span6 centered"
		h1 class="center" Edit expense
		hr
		br
		= render 'form'
		= link_to 'Back', user_expenses_path(current_user), class: 'btn btn-large btn-inverse span6 centered'

app/views/expenses/index.html.slim
div class="row-fluid"
	div	class="span12"
		h1 List of all expenses
		br
		div class="row-fluid"
			div	class="span6"
				= link_to 'Back', root_path, class: 'btn btn-large btn-inverse span5'
			div class="span6"
				= link_to 'New expense', new_user_expense_path(current_user), class: "btn btn-large btn-danger span5 pull-right"
		br
		- if current_user
			table class="table"
				thead
					tr
						th Name
						th Amount
						th Created
						th
						th
				tbody
					- @user.expenses.each do |expense|
						tr
				 			td = link_to expense.name, @expense
				 			td = number_to_currency(expense.value, unit: " ")
				 			td
				 				= expense.created_at.strftime("%Y-%m-%d %H:%M")
				 				| h
				 			td = link_to 'Edit', edit_user_expense_path(current_user, expense), class: "btn btn-small btn-warning"
				 			td = link_to 'Remove', [expense.user, expense], class: "btn btn-small btn-danger", :confirm => 'Are you sure?', :method => :delete
					end
		- else
			div class="row-fluid"
				hr
				h3 class="span6 centered" Log in or sign up to acces your expenses!
		end

app/views/expenses/new.html.slim
div class="row-fluid"
	div class="span6 centered"
		h1 class="center" Add new expense
		hr
		br
		= render 'form'
		= link_to 'Back', user_expenses_path(current_user), class: 'btn btn-large btn-inverse span6 centered'

app/views/expenses/show.html.slim
div class="row-fluid"
	div class="span6 centered"
		h1 class="center" Expense view
		hr
		br
		div class="center"
			h3
				= @expense.name
				= number_to_currency(@expense.value, unit: " ")
		div class="center"
			h4 
				| Date created: &nbsp;
				= @expense.created_at.strftime("%Y-%m-%d %H:%M")
			 	| h
			= link_to 'Back', expenses_path, class: 'btn btn-large btn-inverse span5 centered'

app/views/incomes/_form.html.slim
- if current_user
	= form_for ([@user, @user.incomes.build]), html: {class: "form"} do |f|
		- if @income.errors.any?
			div id="error_explanation" class="alert alert-error"
				button type="button" class="close" data-dismiss="alert"&times;
				h4 class="center"
					= pluralize(@income.errors.count, "error")
					| &nbsp;!
				ul
				- @income.errors.full_messages.each do |msg|
					li class="list-style-none center" = msg
				end
		end
		fieldset class="center"
			= f.text_field :name, value: controller.action_name == 'edit' || controller.action_name == 'update'  ? @income.name : @income.name, class: "span6", placeholder: "Income name"
			br
			= f.text_field :value, value: controller.action_name == 'edit' || controller.action_name == 'update'  ? number_to_currency(@income.value, unit: " ") : number_to_currency(@income.value, unit: " "), class: "span6", placeholder: "Amount"
			br
			= f.submit 'Add', class: 'btn btn-large btn-success span6'   		
	end
- else
	div class="row-fluid"		
		h3 class="span6 centered" Log in or sign up to add new income!
		hr
end

app/views/incomes/edit.html.slim
div class="row-fluid"
	div class="span6 centered"
		h1 class="center" Edit income
		hr
		br
		= render 'form'
		= link_to 'Back', user_incomes_path(current_user), class: 'btn btn-large btn-inverse span6 centered'

app/views/incomes/index.html.slim
div class="row-fluid"
	div	class="span12"
		h1 List of all incomes
		br
		div class="row-fluid"
			div	class="span6"
				= link_to 'Back', root_path, class: 'btn btn-large btn-inverse span5'
			div class="span6"
				= link_to 'New income', new_user_income_path(current_user), class: "btn btn-large btn-success span5 pull-right"
		br
		- if current_user
			table class="table"
				thead
					tr
						th Name
						th Amount
						th Created
						th
						th
				tbody
					- @user.incomes.each do |income|
						tr
				 			td = link_to income.name, @income
				 			td = number_to_currency(income.value, unit: " ")
				 			td
				 				= income.created_at.strftime("%Y-%m-%d %H:%M")
				 				| h
				 			td = link_to 'Edit', edit_user_income_path(current_user, income), class: "btn btn-small btn-warning"
				 			td = link_to 'Remove', [income.user, income], class: "btn btn-small btn-danger", :confirm => 'Are you sure?', :method => :delete
					end 
			br
		- else
			div class="row-fluid"
				hr
				h3 class="span6 centered" Log in or sign up to acces your incomes!
		end

app/views/incomes/new.html.slim
div class="row-fluid"
	div class="span6 centered"
		h1 class="center" Add new income
		hr
		br
		= render 'form'
		= link_to 'Back', user_incomes_path(current_user), class: 'btn btn-large btn-inverse span6 centered'

app/views/incomes/show.html.slim
div class="row-fluid"
	div class="span6 centered"
		h1 class="center" Income view
		hr
		br
		div class="center"
			h3
				= @income.name
				= number_to_currency(@income.value, unit: " ")
		div class="center"
			h4 
				| Date created: &nbsp;
				= @income.created_at.strftime("%Y-%m-%d %H:%M")
			 	| h
			= link_to 'Back', incomes_path, class: 'btn btn-large btn-inverse span5 centered'

app/views/layouts/_footer.html.slim
footer
	br
	br
	| © Siniša Mikulić 2013

javascript:
	$(".alert").alert()

app/views/layouts/_navigation.html.slim
div class="row-fluid"
	div class="span8"
		h1 NoExpense
		h3 Track your income and expenses
	div class="span4"
		- if current_user
			div class="row-fluid"
				div class="span12"
					h4 class="pull-right"
						| Welcome, 
					 	= link_to current_user.email, current_user
					 	|  !
			div class="row-fluid"
				div class="span12"
					h4 class="pull-right" = link_to "Log out", log_out_path
		- else
			h4 class="pull-right" 
				= link_to "Sign up", sign_up_path
				|  |
				= link_to "Log in", log_in_path
		end	
br
hr

app/views/layouts/application.html.slim
doctype html
html
	head
		title Noexpense
		= stylesheet_link_tag    "application", :media => "all"
		= javascript_include_tag "application"
		= csrf_meta_tags
		meta name="viewport" content="width=device-width, initial-scale=1.0"
		link href='http://fonts.googleapis.com/css?family=Open+Sans:300,300italic,700' rel='stylesheet' type='text/css'

	body
		div class="container-fluid"
			div class="row"
				div class="span12 centered"
					= render 'layouts/navigation'
					div class="row-fluid"
						div class="span12 centered"
							- flash.each do |name, msg|
								div id="error_explanation" class="alert alert-error"
									button type="button" class="close" data-dismiss="alert"&times;
									ul
										li class="list-style-none center" = content_tag :span, msg, :id => "flash_#{name}"
							end
					= yield
			div class="row"
				div class="span12 centered"
					= render 'layouts/footer'

app/views/main/index.html.slim
- if current_user
	div	class="row-fluid"
		div	class="span12"
			div class="row-fluid"
				div class="span6"
					table class="table"
						tr
							th Income
							th Expenses
							th Balance
						tr
							td = number_to_currency(current_user.incomes.sum('value'), unit: " ")
							td = number_to_currency(current_user.expenses.sum('value'), unit: " ")
							td = number_to_currency(@balance, unit: " ")
				div class="span6"
					div class="row-fluid"
						div	class="span6"
							= link_to "Incomes", user_incomes_path(current_user), class: "btn btn-large btn-info span8"
						div	class="span6"
							= link_to "New Income", new_user_income_path(current_user), class: "btn btn-large btn-success span12"
					hr
					div class="row-fluid"
						div	class="span6"
							= link_to "Expenses", user_expenses_path(current_user), class: "btn btn-large btn-info span8"
						div	class="span6"
							= link_to "New Expense", new_user_expense_path(current_user), class: "btn btn-large btn-danger span12"
- else
	div class="row-fluid"
		hr
		h3 class="span6 centered" Log in or sign up to acces your expenses!
end

app/views/users/_form.html.slim
= form_for @user, html: {class: "form"} do |f|
	- if @user.errors.any?
		div id="error_explanation" class="alert alert-error"
			button type="button" class="close" data-dismiss="alert"&times;
			h4 class="center"
				= pluralize(@user.errors.count, "error")
				| &nbsp;!
			ul
			- @user.errors.full_messages.each do |msg|
				li class="list-style-none center" = msg
			end
	end
	fieldset class="center"
		= f.text_field :email, class: "span6", placeholder: "Email"
		br
		= f.password_field :password, class: "span6", placeholder: "Password"
		br
		= f.password_field :password_confirmation, class: "span6", placeholder: "Password confirmation"
		br
		= f.submit 'Sign Up', class: 'btn btn-large btn-success span6'   		
end

app/views/users/index.html.slim
div class="row-fluid"
	div	class="span12"
		h1 List of all users
		br
		div class="row-fluid"
			div	class="span6"
				= link_to 'Back', root_path, class: 'btn btn-large btn-inverse span5'
			div class="span6"
				= link_to 'New user', new_user_path, class: "btn btn-large btn-danger span5 pull-right"
		br
		- if current_user
			table class="table"
				thead
					tr
						th Email
						th
						th
				tbody
					- @users.each do |user|
						tr
				 			td = link_to user.email, user
				 			td = link_to 'Edit', edit_user_path(user), class: "btn btn-small btn-warning"
				 			td = link_to 'Remove', user, class: "btn btn-small btn-danger", :confirm => 'Are you sure?', :method => :delete
					end
		- else
			div class="row-fluid"
				hr
				h3 class="span6 centered" Log in or sign up to see all users!
		end

app/views/users/new.html.slim
div class="row-fluid"
	div class="span6 centered"
		h1 class="center" Sign up
		hr
		br
		= render 'form'
		= link_to 'Back', root_path, class: 'btn btn-large btn-inverse span6 centered'

app/views/users/show.html.slim
= link_to "Add expense", user_expenses_path(current_user), class: "btn btn-large btn-danger span12"
br

= form_for([@user, @user.expenses.build]) do |f|
	fieldset class="center"
		= f.text_field :name, class: "span6", placeholder: "Expense name"
		br
		= f.text_field :value, class: "span6", placeholder: "Amount"
		br
		= f.submit 'Add', class: 'btn btn-large btn-success span6' 
end

div class="row-fluid"
	div class="span6"
		h4 Expenses
		- if current_user
			table class="table"
				thead
					tr
						th Name
						th Amount
						th
				tbody
					- @user.expenses.each do |expense|
						tr
				 			td = link_to expense.name, @expense
				 			td = number_to_currency(expense.value, unit: " ")
				 			td = link_to 'Remove', [expense.user, expense], class: "btn btn-small btn-danger", :confirm => 'Are you sure?', :method => :delete
					end
		- else
			div class="row-fluid"
				hr
				h3 class="span6 centered" Log in or sign up to acces your expenses!
		end
	div class="span6"
		= Expense.sum('value')